# Generated by Django 3.2.8 on 2022-01-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssoffices', '0005_alter_ssstaff_last_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ssstaff',
            index=models.Index(fields=['type'], name='ssoffices_s_type_b3eed0_idx'),
        ),
    ]
