# Generated by Django 3.0.11 on 2021-02-14 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ssoffices', '0001_initial'),
    ]

    operations = [
        ]


