# Generated by Django 3.2.8 on 2021-11-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssoffices', '0002_auto_20211108_1618'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ssstaff',
            index=models.Index(fields=['last_name', 'first_name'], name='ssoffices_s_last_na_ef3fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='ssstaff',
            index=models.Index(fields=['ssoffice'], name='ssoffices_s_ssoffic_b83b54_idx'),
        ),
    ]
