# Generated by Django 3.2.8 on 2022-01-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssoffices', '0004_auto_20211201_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssstaff',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
