# Generated by Django 3.2.6 on 2021-09-25 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Email'), (2, 'Call'), (3, 'Document'), (4, 'Note'), (5, 'SMS'), (6, 'Event')], default=0)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('content_author_note', models.CharField(blank=True, max_length=100)),
                ('in_out', models.IntegerField(choices=[(0, 'Unknown'), (1, 'In'), (2, 'Out'), (3, 'N/A')], default=0)),
                ('content_date', models.DateField(blank=True)),
                ('start', models.DateTimeField(blank=True)),
                ('end', models.DateTimeField(blank=True)),
                ('location', models.CharField(blank=True, max_length=60)),
                ('organizer', models.CharField(blank=True, max_length=60)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('cid_info', models.CharField(blank=True, max_length=30)),
                ('voice_file', models.FileField(upload_to='')),
                ('incoming_medium', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Mail'), (2, 'Email'), (3, 'Fax'), (4, 'SMS'), (5, 'Hand'), (6, 'Dictation'), (9, 'Other')], default=0)),
                ('new', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'New'), (2, 'Active'), (3, 'Draft'), (4, 'Sent'), (5, 'Other')], default=0)),
                ('status_note', models.CharField(blank=True, max_length=80)),
                ('is_billable', models.BooleanField(default=False)),
                ('time_spent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date_received', models.DateField(blank=True)),
                ('date_started', models.DateField(blank=True)),
                ('date_sent', models.DateField(blank=True)),
                ('recipient_type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Client'), (2, 'SS Field Office'), (3, 'SS DDS'), (4, 'SS Hearing Office'), (5, 'SS Service Center'), (6, 'SS Appeals Council'), (7, 'Federal Court'), (8, 'Ins Co'), (9, 'Our Firm'), (10, 'Healthcare Provider'), (11, 'Employer'), (12, 'Other')], default=0)),
                ('recipient', models.CharField(default='unk', max_length=80)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
