# Generated by Django 3.2.6 on 2021-09-25 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matters.matter'),
        ),
        migrations.AddField(
            model_name='entry',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
