# Generated by Django 3.2.8 on 2021-11-08 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterSubTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('UNK', 'Unknown'), ('SS', 'Social Security/SSI'), ('DI', 'STD/LTD/ID'), ('MC', 'Medicare'), ('MH', 'MassHealth'), ('EMP', 'Employment'), ('UIB', 'Unemployoment Benefits'), ('CR', 'Credit/Loan'), ('MIS', 'Miscelenous')], max_length=128, null=True)),
                ('slug', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_opened', models.DateField(null=True)),
                ('date_closed', models.DateField(null=True)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed'), ('RTC', 'Ready to Close')], max_length=128)),
                ('notes', models.TextField(blank=True, max_length=128, null=True)),
                ('is_prospect', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Matter',
                'verbose_name_plural': 'Matters',
                'ordering': ['slug'],
            },
        ),
    ]
