# Generated by Django 3.2.8 on 2021-11-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='is_prospect',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='status',
            field=models.CharField(blank=True, choices=[('OP', 'Open'), ('CL', 'Closed'), ('RTC', 'Ready to Close')], max_length=128, null=True),
        ),
    ]
